version: 2.1

jobs:
  lint:
    executor: cypress-executor
    steps:
      - checkout
      - install-dependencies
      - run: yarn run prettylint "src/**/*.[jt]s?(x)"

  build:
    executor: cypress-executor
    steps:
      - checkout
      - install-dependencies
      - run: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  cypress:
    executor: cypress-executor
    steps:
      - checkout
      - install-dependencies
      - attach_workspace:
          at: ~/project
      - run:
          name: Run server
          command: yarn run serve -s build
          background: true
      - run:
          name: Run cypress tests
          command: yarn run cypress run --record
          environment:
            CYPRESS_baseUrl: http://localhost:5000
            TZ: 'America/New_York'

workflows:
  build:
    jobs:
      - lint
      - build
      - cypress:
          requires:
            - build

executors:
  cypress-executor:
    docker:
      - image: cypress/base:10

commands:
  install-dependencies:
    steps:
      - restore_cache:
          keys:
            - node-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: node-cache-{{ checksum "yarn.lock" }}
          paths:
            node_modules
            ~/.cache
